### ISSUE TITLE
TreeBuilder issue

### ISSUE THREAD

**Issue by emiliesappracone** [stefandoorn/sitemap-plugin#204]
I try to install the repository with : 

php7.4 & php7.3

I have an issue when I run `composer require` : 

```
!!  PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /home/emilie/syliustest/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/Configuration.php on line 18 and at least 1 expected in /home/emilie/syliustest/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
!!  Stack trace:
!!  #0 /home/emilie/syliustest/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/Configuration.php(18): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
!!  #1 /home/emilie/syliustest/vendor/symfony/config/Definition/Processor.php(46): SitemapPlugin\DependencyInjection\Configuration->getConfigTreeBuilder()
!!  #2 /home/emilie/syliustest/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration()
!!  #3 /home/emilie/syliustest/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/SitemapExtension.php(23): Symfony\Component\DependencyInjection\Exte in /home/emilie/syliustest/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
```

How to fix this issue ?

**Comment by stefandoorn** [comment]
What's the exact `composer require` line you are using? Are you installing the alpha of v2?

**Comment by horo42** [comment]
Similiar fix needed to this:
https://github.com/manasbala/doctrine-log-bundle/pull/6/files

I applied the same changes in the Configuration.php and it worked for me.

**Comment by stefandoorn** [comment]
Thanks for the update! I will soon release a v2.0.0 :-)
